name: Run make-zip on each push
run-name: Run make-zip
on:
  push:
    branches:
      - main
jobs:
  make-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Run "npm install"
        run: npm install
        working-directory: ./tools/make-zip
      - name: Run make-zip.js
        run: node make-zip.js
        working-directory: ./tools/make-zip
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: out.zip
          path: ./tools/make-zip/out.zip